### PR TITLE
Rapid JSON v1.1.0 update

### PR DESCRIPTION
**Pull request by leongor**

### CODE REVIEW

**Comment by rnostream** [comment]
+1
rapidJSON license (MIT -Tencent part- and BSD -msinttypes by Alexander Chemeris-) have to be included in the projects root license file.

**Comment by brandtol** [comment]
+1

**Comment by schulz2** [comment]
@leongor: Going to merge a.s.a.p. ... anything more you wanted to add before the merge?

**Comment by schulz2** [comment]
I have double-checked that the license.txt file is included with the rapidJSON source files in the same directory. According to what is suggested in rapidJSON's license text, the problematic JSON license has been removed and I did not see any references to JSON_checker/jsonchecker in what we include. Thus the part of the license that failed our internal tests have been correctly removed and we are on the safe side.

**Pull request merged**
