### PR TITLE
I18n foundation - First delivery of translation work

### PR DESCRIPTION
**Pull request by schulz2**

### CODE REVIEW

**Comment by schulz2** [comment]
If there are no objections I will merge this pull request tomorrow.

**Comment by ddebrunner** [comment]
Sorry, the older pull request changed the version number in info.xml so you need to fix that conflict.

Ideally pull requests don't include formatting changes of code that is not changed, which simplifies the review and reduces the chances of merge conflicts.

**Comment by schulz2** [comment]
Hi @ddebrunner,
is this better now?

**Comment by schulz2** [comment]
Changed copyright header according to what I found in other toolkits.
RTC build scripts adapted for build system and automated test according to toolkit wiki.
RTC test suite has been successfully run.
Resolved merge conflicts.

Ready to pull now?

**Pull request merged**
