### PR TITLE
Decimal type is handled literally (no cast from double).

### PR DESCRIPTION
**Pull request by leongor**
1. Decimal type is handled literally (no cast from double).
2. Regression fix for status handling.

### CODE REVIEW

**Comment by markheger** [comment]
@leongor Could you please describe the changed behaviour in operator description, e.g. SPL decimals types are not converted from double and taken as string.

**Comment by leongor** [comment]
RapidJSON doesn't support natively  parsing high precision decimal values.
The first solution was to parse them as double, then cast to decimal - such approach can loose precision or distort the number.
The current solution is to parse the JSON value as a string, then to cast it using spl_cast to decimal.

**Comment by schulz2** [comment]
Hi @leongor ,
have you added your explanation to the operator description, too, and simply forgotten to push your changes?
Kind regards
Norbert

**Comment by leongor** [comment]
Sorry @shulz2, did not get your question.
It's about native function implementation, why should it be in operator description?

**Comment by schulz2** [comment]
Hi @leongor,
no need to be sorry, the error is on my side. Just saw Mark's request and your answer w/o an accompanying documentation change, so I assumed you forgot to deliver something. Sorry for that ...
Kind regards
Norbert

**Pull request merged**
