### PR TITLE
Native C++ functions to format any SPL type to JSON

### PR DESCRIPTION
**Pull request by leongor**
There are 3 functions:

rstring tupleToJson(Tuple) - format any tuple to JSON.

rstring mapToJson(Map) - format any map to JSON. Key must be rstring or ustring.

rstring splToJson(String, AnySPL) - format any SPL type to JSON with a given key. Key must be rstring or ustring.

### CODE REVIEW

**Comment by chanskw** [comment]
I am curious. What are the rationale to creating these functions ? Why did we implement this in c++ rather than Java ?

I guess the main question is. What can these functions do that cannot be accomplished by the operators ?

**Comment by leongor** [comment]
You can run it in any place you use SPL.
You can run it in a loop.

2015-11-25 22:55 GMT+02:00 Samantha Chan <notifications@github.com>:

> I am curious. What are the rationale to creating these functions ? Why did
> we implement this in c++ rather than Java ?
>
> I guess the main question is. What can these functions do that cannot be
> accomplished by the operators ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBMStreams/streamsx.json/pull/37#issuecomment-159729581>
> .
>



-- 
Best regards,
Leonid Gorelik.

**Comment by apyasic** [comment]
Its not always convenient to pass through additional operator for converting tuple to json. For example,
if you want to run a loop that converts each set element to json and submits it. With native function the code is clean and clear. With operator you should path through additional operator just for conversion purposes and pay operator communication and management price.

**Comment by ddebrunner** [comment]
-1 to the pull request in its current form. The licencing terms for rapidjson requires that a copy of ther permission notices is included in the distribution, but I don't see a copy of license.txt in the pull request.
https://github.com/miloyip/rapidjson/blob/master/license.txt

Maybe some background on why rapidcode source code is copied into this source repo, would it be possible to just pull from the other repo?

Any testing to ensure that the format of the json is the same for these functions as for the operators?

**Comment by ddebrunner** [comment]
It be useful to have SPLDOC descriptions for the functions, so that users of the toolkit can understand how to call them.

**Comment by ddebrunner** [comment]
The operators using JSON in the name, should these functions be consistent with that? E.g. tupleToJSON()?

**Comment by leongor** [comment]
Additional reason of using native functions is simplicity: tupleToJSON and mapToJSON have only 1 parameter - a tuple and a map correspondingly, splToJSON can have any SPL value as parameter, but a key should be provided.

**Comment by ddebrunner** [comment]
Can `splToJson` be renamed to just `toJSON`, since it's not converting SPL to JSON, it's just converting its value (argument) to JSON.

**Comment by leongor** [comment]
@ddebrunner, agree, sounds better.

**Comment by hardeys** [comment]
Hi Leonid,

Does tupleToJson function works similar to TupleToJson Operator in the toolkit. We used this toolkit as part of the solution and had performance issues with Java Based JSON parsor operators. We are currently in process of exploring C++ option as the intial results were better. It will be good to try this new functions if they work the same way.

**Comment by ddebrunner** [comment]
@leongor Still interested in what exactly is the situation with rapidjson is, is it a faithful copy, subset, modified?

**Comment by leongor** [comment]
@hardeys tupleToJSON (already renamed) works very similar TupleToJSON operator, but it simpler.
pros:
It allows to to convert any tuple to JSON, just pass it as a function argument.
cons:
You cannot choose part of the tuple.
Regarding performance - rapidjson is one of the fastest c++ json libraries, so it should be fast, but I didn't measure it yet.

@ddebrunner rapidjson is a header only library, so I copied the whole include dir to the toolkit. The only thirdparty is used by rapidjson is gtest (for tests only) and it comes in a separate thirdparty dir that was not copied to the toolkit.

**Comment by chanskw** [comment]
@ddebrunner can you please take a look at the latest pull request and see if it is ready to be merged?

Thanks!

**Comment by chanskw** [comment]
@ddebrunner ping... any news here?

**Comment by ddebrunner** [comment]
Sorry, I'l take a look at it now

**Comment by ddebrunner** [comment]
Some items that probably need to be cleaned up in future requests, and probably before any release:

* Namespace for the functions is 'json', I'm no C++ expert but that seems wrong, not sure if there is a policy for namespaces for use by IBMStreams toolkit, maybe a namespace matching the toolkit project (streamsx.json) or the toolkitnam (com.ibm.streamsx.json).
* SPLDOC for the functions
* Tests

**Comment by vdogaru** [comment]
- I think it is important (and I agree with @ddebrunner) to use a namespace which is specific for the toolkit and avoid clashes with JSON implementations that other toolkits might provide.
- Any plans for contributing JSON parsing SPL functions?

**Comment by ddebrunner** [comment]
I'll merge this and change the toolkit version number and fix the namespace issue.

**Comment by chanskw** [comment]
Thanks a lot! @ddebrunner

**Comment by leongor** [comment]
@ddebrunner Thanks for merging. Since I've opened this pull request I've fixed few issues after testing these functions on Power Linux. Do I need to open new pull request for them?

**Comment by ddebrunner** [comment]
Yes.

While the pull request is open any new commits added to the same branch and pushed to github are automatically added to the pull request. Once it is merged a new request is needed.

**Comment by ddebrunner** [comment]
@leongor Any chance you can add SPLDOC for the functions so people can understand exactly what they do, rather than having to guess.

**Comment by ddebrunner** [comment]
Merge request #51 bumps the version number and changes the namespace.

**Comment by leongor** [comment]
@ddebrunner I will add SPLDOC.

**Comment by ddebrunner** [comment]
@leongor I added #55 to track the addition of SPLDOC.

**Comment by conglisc** [comment]
Hi @leongor , any update on the SPLDOC.

**Comment by ddebrunner** [comment]
@leongor or for that matter the fixes you mentioned above?

**Comment by leongor** [comment]
I tried to push it to the repository, but I have no authority to do that. What is the process then? Do I need to fork it again and ask for a merge?

-----Original Message-----

**Comment by ddebrunner** [comment]
You create a pull request.

**Comment by conglisc** [comment]
Hi @leongor ,

Did you figure out how to deliver your changes? You can push it to your fork (https://github.com/leongor/streamsx.json) first, then create a pull request.

**Pull request merged**
